config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  resources :books
  resources :users
  resources :authors
    
  get 'users/:id/confirm_delete', to: 'users#confirm_delete', as: 'confirm_delete_user'

  get 'authors/:id/confirm_delete', to: 'authors#confirm_delete', as: 'confirm_delete_author'
    
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books    
    
  validates_presence_of :name
  validates_length_of :name, maximum: 70
    
  def num_books
     books.length     
  end
    
  # Creates and array of arrays to use in dropdown selects for author. For more info:  
  # https://guides.rubyonrails.org/form_helpers.html#select-boxes-for-dealing-with-model-objects
  def self.to_nested_array_for_select
     nested = []  
     Author.order(:name).each do |author|
         nested.push [author.name, author.id]
     end
     return nested 
  end
    

    
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
 
  validates_presence_of :title
  validates_length_of :title, maximum: 255
  validates_presence_of :year
  validates_numericality_of :year, only_integer: true, greater_than: 0, less_than: 2500  

  # Order books by year, author.name, or title
  def self.order_by field
    if field == 'year'
      return Book.order(:year, :title)
    elsif field == 'author'
      return Book.joins(:author).order(:name, :year)
    else
      return Book.order(:title)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord   
    validates_presence_of :name
    validates_length_of :name, maximum: 70    
    validates_presence_of :email
    validates_length_of :email, maximum: 255
    validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  # GET /authors
  def index
    @authors = Author.all
  end

  # GET /authors/:id
  def show
    @author = Author.find(params[:id])
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/:id/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  def create
    # active record new, create, and update allow us to pass in a hash with the
    # attributes and their values, author_params is a method (see below!)      
    @author = Author.new(author_params)

    if @author.save
      flash[:notice] = 'Author was successfully created.' 
      redirect_to @author
    else
      render :new
    end
  end

  # PATCH/PUT /authors/:id
  def update
    @author = Author.find(params[:id])      
    if @author.update(author_params)
      flash[:notice] = 'Author was successfully updated.' 
      redirect_to @author 
    else
      render :edit
    end
  end

  # GET /authors/:id/confirm_delete  
  def confirm_delete
      @author = Author.find(params[:id])
      # show the form for confirm_delete of user 
  end        
    
  # DELETE /authors/:id
  def destroy
    @author = Author.find(params[:id])  
    if @author.destroy
        flash[:notice] = 'Author was successfully deleted.'
    else
        flash[:notice] = 'Unable to delete author.'
    end
    redirect_to authors_url 
  end

  private
    # Only allow a trusted parameter "white list" through.
    def author_params
      # params is a hashtable.  It should have in it a key of :author.
      # The value for the :author key is another hash.
      # If params does not contain the key :author, an exception is raised.  
      # Only the "author" hash is returned and only with the permitted key(s).
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # GET /books
  def index
    # We've added a method, self.order_by, to the Book model, 
    # see models/book.rb
    @books = Book.order_by params[:order_by]
  end

  # GET /books/:id
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/:id/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  def create
    # active record new, create, and update allow us to pass in a hash with the
    # attributes and their values, book_params is a method (see below!)
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = 'Book was successfully created.'  
      redirect_to @book
    else
      render :new
    end
  end

  # PATCH/PUT /books/:id
  def update
    @book = Book.find(params[:id])  
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.' 
      redirect_to @book
    else
      render :edit
    end
  end

  # DELETE /books/:id
  def destroy
    @book = Book.find(params[:id])  
    if @book.destroy
        flash[:notice] = 'Book was successfully deleted.'
    else
        flash[:notice] = 'Unable to delete book.'
    end
    redirect_to books_url 
  end

  private
    # Only allow a trusted parameter "white list" through.
    def book_params
      # params is a hashtable.  It should have in it a key of :book.
      # The value for the :book key is another hash.
      # If params does not contain the key :book, an exception is raised.  
      # Only the "book" hash is returned and only with the permitted key(s).
      # So returns a hash with only having at most keys of :title, :year, :author_id
      params.require(:book).permit(:title, :year, :author_id)
    end
      
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # This controller is only here to render the template 
  # static_pages/home.html.erb, which we use as the root of the application
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/:id
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    # active record new, create, and update allow us to pass in a hash with the
    # attributes and their values, user_params is a method (see below!)
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'User was successfully created.'  
      redirect_to @user
    else
      render :new
    end
  end

  # PATCH/PUT /users/:id
  def update
    @user = User.find(params[:id])  
    if @user.update(user_params)
      flash[:notice] = 'User was successfully updated.'
      redirect_to @user
    else
      render :edit
    end
  end

  def confirm_delete
      @user = User.find(params[:id])
      # show the form for confirm_delete of user 
  end
    
  # DELETE /users/:id
  def destroy
    @user = User.find(params[:id])  
      
    if @user.destroy
        flash[:notice] = 'User was successfully deleted.'
    else
        flash[:notice] = 'Unable to delete user.'
    end
      
    redirect_to users_url        
  end

  private
    # Only allow a trusted parameter "white list" through.
    def user_params
      # params is a hashtable.  It should have in it a key of :user.
      # The value for the :user key is another hash.
      # If params does not contain the key :user, an exception is raised.  
      # Only the "user" hash is returned and only with the permitted key(s).
      # So we get back { :name => someName, :email => someEmail}
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/confirm_delete.html.erb
<h1>Delete Author</h1>
<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>
<% if @author.num_books > 0 %>    
  <p>
    <strong>Notice:</strong> This author has <%= @author.num_books %> book(s).  You must first delete the author's books before deleting the author.
  </p>
<% else %>
  <%= form_with model: @author, local: true, method: 'delete' do |f| %>
    <%= f.submit "Confirm Delete" %>
  <% end %>
<% end %>

<p>
<%= link_to 'Edit Author', edit_author_path(@author) %> |    
<%= link_to 'Show Authors', authors_path %> |
<%= link_to 'Home', root_path %> 
</p>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<p>
<%= link_to 'Show Authors', authors_path %> |
<%= link_to 'Home', root_path %> 
</p>

app/views/authors/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.order(:name).each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Delete', confirm_delete_author_path(author) %></td>     
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
<%= link_to 'New Author', new_author_path %> |
<%= link_to 'Home', root_path %> 
</p>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<p>
<%= link_to 'Show Authors', authors_path %> |
<%= link_to 'Home', root_path %> 
</p>

app/views/authors/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>

<p><%= link_to 'Edit Author', edit_author_path(@author) %></p>
    
</p>

<p>
<%= link_to 'New Author', new_author_path %> |
<%= link_to 'Show Authors', authors_path %> |
<%= link_to 'Home', root_path %> 
</p>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.select(:author_id, Author.to_nested_array_for_select) %>      
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<p>
<%= link_to 'Show Books', books_path %> |
<%= link_to 'Home', root_path %>
</p>

app/views/books/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th><%= link_to 'Title', books_path(order_by: 'title') %></th>
      <th><%= link_to 'Year', books_path(order_by: 'year') %></th>
      <th><%= link_to 'Author', books_path(order_by: 'author') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.year %></td>
        <td><%= book.author.name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= form_with model: book, method: :delete, local: true do |f| %>
            <%= f.submit 'Delete' %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<p>
<%= link_to 'New Book', new_book_path %> |
<%= link_to "Home", root_path %>    
</p>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<p>
<%= link_to 'Show Books', books_path %> |
<%= link_to "Home", root_path %>    
</p>    

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @book.year %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author.name %>
</p>
<p>
<%= link_to 'Edit Book', edit_book_path(@book) %> |
<%= link_to 'Show Books', books_path %> |
<%= link_to "Home", root_path %>    
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Betterbooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>BetterBooks</h1>
<p><%= link_to "Authors", authors_path %></p>
<p><%= link_to "Books", books_path %></p>
<p><%= link_to "Users", users_path %></p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prevented this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/confirm_delete.html.erb
<h1>Delete User</h1>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= form_with model: @user, local: true, method: 'delete' do |f| %>
<%= f.submit "Confirm Delete" %>
<% end %>

<p>
<%= link_to 'Show Users', users_path %> | 
<%= link_to "Home", root_path %>
</p>    

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<p>
<%= link_to 'Show Users', users_path %> | 
<%= link_to "Home", root_path %>
</p>    

app/views/users/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', confirm_delete_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
<%= link_to 'New User', new_user_path %> |
<%= link_to "Home", root_path %>    
</p>    

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<p>
<%= link_to 'Show Users', users_path %> | 
<%= link_to "Home", root_path %>
</p>    

app/views/users/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
<%= link_to 'Edit User', edit_user_path(@user) %> |
<%= link_to 'Show Users', users_path %> |
<%= link_to "Home", root_path %>
</p>